interface AppInfo {
  signature1: string;
  signature2: string;
  environment: string;
  name: string;
  url: string;
  packageName: string;
  bundleUid: string;
  bundleName: string;
  isMasterBundle: string;
  bundleInstalled: string;
  oauthProtocol: string;
  oauthDomain: string;
  oauthPort: string;
  oauthPrefix: string;
  proxyProtocol: string;
  proxyDomain: string;
  proxyDomainAlias: string;
  proxyPort: string;
  apiProtocol: string;
  apiDomain: string;
  apiPort: string;
  phpProtocol: string;
  phpDomain: string;
  phpPort: string;
  phpXProtocol: string;
  phpXDomain: string;
  phpXPort: string;
  redirectFromPort: string;
  translationsUrl: string;
  privacyPolicyUrl: string;
  termsOfUseUrl: string;
  streamingProtocol: string;
  streamingDomain: string;
  streamingPort: string;
  sslMaintainer: string;
  webProtocol: string;
  webDomain: string;
  webPort: string;
  sslCert: string;
  sslKey: string;
  sslCa: string;
  sslChain: string;
  sslFullchain: string;
  assetServiceUrl: string;
}

export type { AppInfo };
